abndetect/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^identify/', include('identify.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

identify/urls.py
from django.conf.urls import url
from . import views

app_name = 'identify'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^index$', views.index, name='index'),
    url(r'^search$', views.search, name='search'),
    url(r'^history$', views.history, name='history'),
]

identify/models.py
from django.db import models


class Xray(models.Model):
    condition = models.CharField(max_length=15)
    body_part = models.CharField(max_length=15)
    patient = models.CharField(max_length=100)
    bone_image = models.FileField()
    probability = models.CharField(max_length=10)

    def __str__(self):
        return self.condition + self.body_part + self.patient

identify/forms.py
from django import forms
from .models import Xray


class boneform(forms.ModelForm):
    class Meta:
        model = Xray
        fields = ['patient', 'bone_image']

identify/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Xray
from django.template import loader
from .forms import boneform
from keras.preprocessing.image import image
import numpy as np
from .cnn import finger, elbow, humerus, wrist, hand, forearm, shoulder, body_part_classifier



# Create your views here.

def predict(request):
    ans = ['elbow', 'forearm', 'finger', 'hand', 'humerus', 'shoulder', 'wrist']
    need = Xray.objects.last()
    predict_path = "media/" + str(need.bone_image)
    test_image = image.load_img(predict_path, target_size=(224,224))
    test_image = image.img_to_array(test_image)
    test_image = np.expand_dims(test_image, axis=0)
    result = body_part_classifier.predict(test_image)
    ans2 = 0
    result = result[0]
    result = result.tolist()
    i = 0
    for x in result:
        if x == 1:
            ans2 = ans[i]
        i = i + 1
    need.body_part = ans2
    body_part = ans2
    if body_part == 'elbow':
        condition_classifier = elbow
    elif body_part == 'forearm':
        condition_classifier = forearm
    elif body_part == 'finger':
        condition_classifier = finger
    elif body_part == 'hand':
        condition_classifier = hand
    elif body_part == 'humerus':
        condition_classifier = humerus
    elif body_part == 'wrist':
        condition_classifier = wrist
    elif body_part == 'shoulder':
        condition_classifier = shoulder
    result2 = condition_classifier.predict(test_image)
    result2 = result2[0]
    result2 = result2.tolist()
    condition = 'positive'
    prob = result2[0]
    if result2[1] > result2[0]:
        condition = 'negative'
        prob = result2[1]
    need.condition = condition
    p = prob
    print(str(prob))
    prob = prob*100
    prob = str(round(prob, 2))+"%"
    need.probability = prob
    need.save()
    if p > 0.7:
        prob = "Consultation strongly Advised! High Risk!"
    elif p > .5:
        prob = "Consultation advised, low risk involved."
    else:
        prob = "Exercise advised."
    context = {
        'ans2': ans2,
        'condition':condition,
        'need': need,
        'prob': prob,
    }
    return context



def home(request):
    template = loader.get_template('identify/home.html')
    return HttpResponse(template.render())

def index(request):
    if request.method == 'POST':
        form = boneform(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            context = predict(request)
            template = loader.get_template('identify/prediction.html')
            return HttpResponse(template.render(context, request))
    else:
        form = boneform()
        return render(request, 'identify/index.html', {'form': form})


def search(request):
    fil = request.GET['q']
    images = Xray.objects.filter(patient=fil)
    probs = []
    for i in images:
        p = i.probability[:1]
        if p == '':
        	p = '0'
        p = int(p)
        #print("PROASDASDSAFDSAFDSFASDFSADF  " + p)
        if p > 7:
            prob = "Consultation strongly Advised! High Risk!"
        elif p > 5:
            prob = "Consultation advised, low risk involved."
        else:
            prob = "Exercise advised."
        probs.append(prob)
    context = {
        'all_images': images,
        'probs': probs,
    }
    template = loader.get_template('identify/search.html')
    return HttpResponse(template.render(context, request))


def history(request):
    images = Xray.objects.all()
    probs = []
    for i in images:
        p = i.probability[:1]
        if p == '':
            p = '0'
        p = int(p)
        if p > 7:
            prob = "Consultation strongly Advised! High Risk!"
        elif p > 5:
            prob = "Consultation advised, low risk involved."
        else:
            prob = "Exercise advised."
        probs.append(prob)
    context = {
        'all_images': images,
        'probs': probs,
    }
    template = loader.get_template('identify/search.html')
    return HttpResponse(template.render(context, request))


identify/templates/identify/home.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>MURA V1.1</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'identify/button.css' %}">
</head>
<body>
		<header>
			<div class="containr">
				<div class="logo">
					<img src="{% static 'identify/logo.jpg' %}" height="100" width="250">
				</div>
				<nav class="navi">
					<!--div>
						<li><button class="butt">Home</button></li>
						<li><button class="butt">About</button></li>

						<li>
							<select id="on">
								<option value="0" class="one">More:</option>
		   						<option value="1" class="one">Version</option>
		    					<option value="2" class="one">Suggest</option>
							    <option value="3" class="one">Help</option>
							</select>
						</li> 
					</div-->
					<!--div id="temp">
						<li><button class="rbutt">Contact Us</button></li>
					 <!--	<li><button class="rbutt">Like</button></li>
					</div-->
				</nav>
			</div>
		</header>

		<div id="bod">

			<div id="cont">
				<strong><span id="heading">Instant abnormality detection.<br>
					Get all the information you need in no time.</span></strong>
					<br><br>
				<span id="rest">Want to find out about an X-Ray without incurring heavy fees? Simply take a photo, upload it, and immediately get the results.</span>
			</div>

			<div id="browse">
				 <div class="row-flex columns columns-1">
	             <!--   <div class="item right-border">
	                    <img src="camera.png" class="bodimg">
	                    <p>Identify 4,000+ plants & counting</p>
	                </div> -->
	                <div class="item right-border">
	                    <img src="{% static 'identify/graph.png' %}" class="bodimg">
	                    <p>Unmatched accuracy</p>
	                </div>
	                <div class="item">
	                    <img src="{% static 'identify/result.png' %}" class="bodimg">
	                    <p>Results in less than<br> a second</p>
	                </div>
            	</div>
        <!--    	<div id="form">
					<form action="/action_page.php">
				  		<input type="file" name="pic" accept="image/*">
				  		<span style="color: black"><input type="submit"></span>
					</form>
				</div> -->
			</div>

		</div>

	<!--	<footer>
			<div id="status">
				<div class="foot">
					<select class="flist">
						<option class="fitem">About Us</option>
					</select>
				</div> 
				<div class="foot">
					<select class="flist">
						<option class="fitem">Quick Links</option>
						<option class="fitem"><button class="fbutt">Help</button></option>
						<option class="fitem"><button class="fbutt">About</button></option>
						<option class="fitem"><button class="fbutt">Message</button></option>
					</select>
				</div>  
				<div class="foot">
					<select class="flist">
						<option class="fitem">Links</option>
						<option class="fimg"><a href="#"><img src="9gag.png" class="navimg2"></a></option>
						<option class="fimg"><a href="#"><img src="fb.png" class="navimg2"></a></option>
						<option class="fimg"><a href="#"><img src="tw.jpg" class="navimg2"></a></option>
					</select>
				</div>
			</div>
			<div class="containr" id="last">
				&copy; Dot Machine
			</div>
		</footer> -->
		<a href="{% url 'identify:index' %}" class="iden"><font align="center">DETECT NOW! </font></a>
</body>
</html>


<!--
	<footer>
				<div class="foot">
					<select class="flist">
						<option class="fitem">About Us</option>
					</select>
				</div>
				<div class="foot">
					<select class="flist">
						<option class="fitem">Quick Links</option>
						<option class="fitem"><button class="fbutt">Help</button></option>
						<option class="fitem"><button class="fbutt">About</button></option>
						<option class="fitem"><button class="fbutt">Message</button></option>
					</select>
				</div>
				<div class="foot">
					<select class="flist">
						<option class="fitem">Links</option>
					<option class="fimg"><a href="#"><img src="9gag.png" class="navimg2"></a></option>
					<option class="fimg"><a href="#"><img src="fb.png" class="navimg2"></a></option>
					<option class="fimg"><a href="#"><img src="tw.jpg" class="navimg2"></a></option>
				</select>
				</div>
			</div>
			<div class="containr" id="last">
				&copy; Dot Machine
			</div>
		</footer>


		<footer>
				<div class="foot">
					<h4>About Us</h4>
					<hr>
					Dummy text lorem ipsum
				</div>
				<div class="foot">
					<h4>Quick Links </h4>
					<hr>
					<ul>
						<li><button class="fbutt">Help</button></li>
						<li><button class="fbutt">About</button></li>
						<li><button class="fbutt">Message</button></li>
					</ul>
				</div>
				<div class="foot">
					<h4>Links</h4><hr>
					<li><a href="#"><img src="9gag.png" class="navimg2"></a></li>
					<li><a href="#"><img src="fb.png" class="navimg2"></a></li>
					<li><a href="#"><img src="tw.jpg" class="navimg2"></a></li>
				</div>
			</div>
			<hr>
			<div class="containr" id="last">
				&copy; Dot Machine
			</div>
		</footer>




		<div id="form">
					<form action="#">
				  		<div class="btn btn-primary btn-sm float-left"><input type="file" name="pic" accept="image/*">
				  		</div>
				  		<input type="submit" class="btn btn-primary">
					</form>
				</div>
			</div>
-->


identify/templates/identify/index.html

{% extends 'identify/navbar.html' %}


{% load staticfiles %}
{% block navbar %}

<style>
    body{
        background: url("{% static 'identify/hello.jpg' %}");
        height: 100%;
        min-height: 100%;
    }

    label{
        color: white;
    }
</style>

<div class="div" style="padding-top:130px; padding-left: 100px;">
    <form action="{% url 'identify:index' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label style="font-size: 20px;color: black; " >{{ field.label_tag }}</label >
            <div class="input" name="pop">{{ field }}</div><br/>
        </div>
        {% endfor %}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

identify/templates/identify/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>MURA V1.1</title>
    {% load staticfiles %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'identify/style_navbar.css' %}">

</head>

<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="{% url 'identify:home' %}"><img src="{% static 'identify/logo.jpg' %}" height="60" width="150" ></a>
        </div>
        <div  id="identify_navbar" class="navbar-header">
            <a id="" class="navbar-brand" href="{% url 'identify:index' %}">Identify</a>
        </div>
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'identify:history' %}">History</a>
        </div>
        <div>
            <form class="navbar-form navbar-left" role="search" mehtod="get" action="{% url 'identify:search' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
        </div>
    </div>
</nav>
{%  block navbar %}
{% endblock %}

</body>
</html>

identify/templates/identify/prediction.html
{% extends 'identify/navbar.html' %}
{% load staticfiles %}

<!--link type="text/css" rel="stylesheet" href="{% static 'identify/empty.css' %}"-->

{%  block navbar %}

<div style="text-align: center;" >
    <h1>NOW PREDICTING!</h1><br/>
    <img style="height: 300px; width: 300px; margin-bottom:10px" src={{ need.bone_image.url }}>
    <br/>
    <!--span style="font: 30px bold; text-transform: uppercase;">{{ ans2 }}</span-->
    <br/>
    <span style="font: 30px bold; text-transform: uppercase;">
            {{ need.condition }}
                        {% if need.condition == "positive" %}
                            :{{ prob }}
                        {% endif %}
            </span	>
    <br/>
    <!--span style="font: 30px bold; text-transform: uppercase;">{{ prob }}</span-->

</div>
<!--h1><a href="{% url 'identify:index' %}">Return</a></h1-->
{% endblock %}

identify/templates/identify/search.html
{% extends 'identify/navbar.html' %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    


{% load staticfiles %}
<style>
    body{
        background: url("{% static 'identify/hello.jpg' %}");
        height: 100%;
        min-height: 100%;
    }

    label{
        color: white;
    }
</style>


{% block navbar %}  
    {% if all_images %}
    <table style="text-align: center; width:100%; ">

        {% for image in all_images %}{% for prob in probs %}
        {% if forloop.counter == forloop.parentloop.counter %}
        <tr>
            <td>
                <img style="height: 150px; width: 150px;" src="{{ image.bone_image.url }}">
            </td>
            <td>
                <h3>
                    <label>
                        {{ image.condition }}
                        {% if image.condition == "positive" %}
                            :{{ prob }}
                        {% endif %}
                    </label>
                </h3>
            </td>
        </tr>
        {% endif %}
        {% endfor %}
        {% endfor %}

    </table>

    {% endif %}

{% endblock %}